---
title: "20201201_tidy_tuesday"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
shelters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-12-01/shelters.csv')
shelters
```

```{r}
shelters %>% 
  distinct(sector)
```
```{r}
shelters_1 <- shelters %>% 
  select(id, sector, occupancy, capacity) %>%
  pivot_longer(cols = c(occupancy, capacity), names_to = "metric", values_to = "number")

shelters_1

```
```{r}
p <- ggplot(data = shelters_1,
            mapping = aes(x = number, fill = metric)
            )

p + geom_histogram(position = "dodge")
```

```{r}

capacity_occupancy_plot <- function(xlim = c(0, 900), ylim = c(0, 900)) {
  
  list(geom_point(mapping = aes(colour = sector), alpha = 0.5),
      scale_colour_brewer(type = "qual", palette = "Dark2"),
      coord_cartesian(xlim = xlim, ylim = ylim),
      theme_minimal()
  )  
}

p <- ggplot(data = shelters,
            mapping = aes(x = capacity, y = occupancy))

p + capacity_occupancy_plot() +
        geom_abline(slope = 1, intercept = 0)

p + capacity_occupancy_plot(xlim = c(0, 300), ylim = c(0, 300)) +
          geom_abline(slope = 1, intercept = 0)

```

```{r}
shelters <- shelters %>% 
  filter(capacity > 0) %>% 
  mutate(occupancy_rate = occupancy / capacity)


capacity_ratio_plot <- function(x_max){
    p <- ggplot(data = shelters,
            mapping = aes(capacity, y = occupancy_rate)
            )

    p + capacity_occupancy_plot(xlim = c(0, x_max), ylim = c(0, 5))
}

x_lims <- seq(from = 100, to = 800, by = 200)


x_lims %>% 
  map(~capacity_ratio_plot(.))

# p <- ggplot(data = shelters,
#             mapping = aes(capacity, y = occupancy_rate)
#             )
# 
# p + capacity_occupancy_plot(xlim = c(0, 900), ylim = c(0, 5))
# p + capacity_occupancy_plot(xlim = c(0, 300), ylim = c(0, 5))
```

```{r}
p <- ggplot(data = shelters,
            mapping = aes(x = occupancy_rate)
            )
p + geom_histogram(binwidth = 0.1)
```

```{r}
summary(shelters$occupancy_rate)
```
```{r}
summary(shelters$occupancy)
summary(shelters$capacity)
```
```{r}
shelters %>% 
  distinct(occupancy_date) %>% 
  summarise(max = max(occupancy_date),
            min = min(occupancy_date)
            )
```


```{r}

# focus on 2019 data
shelters_2019 <- shelters %>% 
  filter(occupancy_date >= as.POSIXct("2019-01-01"))

# calculate mean occupancy and capacities of each shelter over 2019
shelters_2019_mean_rates <- shelters_2019 %>% 
  group_by(shelter_name, sector) %>% 
  summarise(mean_occ = mean(occupancy, na.rm = TRUE),
            mean_cap = mean(capacity, na.rm = TRUE)
            ) %>% 
  ungroup()

shelters_2019_mean_rates

```

```{r}
# define break points for binning data
b <- c(0, 5, 10, 25, 50, 100, 250, 500, 1000)

capacity_occupancy <- shelters_2019_mean_rates %>% 
  mutate(perc_capacity = mean_cap / sum(mean_cap),
         perc_occupancy = mean_occ / sum(mean_occ)
         ) %>% 
  
  pivot_longer(cols = c(mean_occ, mean_cap), names_to = "metric", values_to = "number") %>% 
  mutate(bin = cut(number, breaks = b)) %>% 
  
  group_by(bin, metric) %>%
  summarise(perc_cap = sum(perc_capacity),
            perc_occ = sum(perc_occupancy),
            n = n()
            ) %>% 
  
  ungroup()

capacity_occupancy

```
```{r}
cap_occ_df <- capacity_occupancy %>% 
  mutate(value = if_else(metric == "mean_cap", perc_cap, perc_occ)) %>% 
  select(-perc_cap, -perc_occ)

cap_occ_df
  
```
```{r}
p_xlab <- "Number of people"
p_title <- "Homeless Shelters in Toronto"
p_caption <- "Source: open.toronto.ca"

f_labs <- c(`mean_cap` = "Percent of shelter capacity",
            `mean_occ` = "Percent of shelter occupancy")

x_labs <- c("0-5", "5-10", "10-25", "25-50", "50-100", "100-250", "250-500", "500-1000")

p <- ggplot(data = cap_occ_df, 
            mapping = aes(x = bin, y = value, fill = metric)
            )

p + geom_bar(stat = "identity") +
  
  scale_fill_brewer(type = "qual", palette = "Dark2") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(labels = x_labs) +
  
  guides(fill = FALSE) +
  
  theme(strip.text.x = element_text(face = "bold")) +
  labs(y = NULL, x = p_xlab,
       caption = p_caption,
       title = p_title) +
  
  facet_grid(~ metric, labeller = as_labeller(f_labs)) +
  coord_flip() +
  theme_minimal()
```


```{r}
  
# capacity_occupancy <- shelters %>% 
#   select(id, capacity, occupancy) %>% 
#   mutate(perc_capacity = capacity / sum(capacity),
#          perc_occupancy = occupancy / sum(occupancy)
#          ) %>% 
#   pivot_longer(cols = c(occupancy, capacity), names_to = "metric", values_to = "number") %>% 
#   mutate(bin = cut(number, breaks = b)) %>% 
#   
#   group_by(bin, metric) %>%
#   summarise(perc_cap = sum(perc_capacity),
#             perc_occ = sum(perc_occupancy),
#             n =
#             )
#   
# 
# capacity_occupancy
```

```{r}
shelters_2019_capacity <- shelters_2019_mean_rates %>%
  select(-mean_occ) %>% 
  mutate(mean_cap = round(mean_cap)) %>% 
  rename(capacity_2019_mean = mean_cap) %>% 
  mutate(shelter_size = cut(capacity_2019_mean, breaks = b))

shelters_2019_capacity
  
```
```{r}
shelters_2019_cap_by_sec_size <- shelters_2019_capacity %>% 
  group_by(sector) %>% 
  mutate(prop_sector_cap = capacity_2019_mean / sum(capacity_2019_mean)) %>% 
  ungroup() %>% 
  
  group_by(sector, shelter_size) %>% 
  summarise(prop_cap = sum(prop_sector_cap)) %>% 
  mutate(total_cap = sum(prop_cap)) %>% 
  ungroup() %>% 
  
  mutate(shelter_size = fct_relevel(shelter_size, "(0,5]", "(5-10]", "(10-25]", "(25-50]", "(50-100]", "(100-250]", "(250-500]", "(500-1000]"))

shelters_2019_cap_by_sec_size 

```

```{r}
shelters_2019_cap_by_sec_size <- shelters_2019_cap_by_sec_size %>% 
  mutate(shelter_size = fct_recode(shelter_size, 
                                   "0-5" = "(0,5]",
                                   "5-10" = "(5,10]",
                                   "10-25" = "(10,25]",
                                   "25-50" = "(25,50]",
                                   "50-100" = "(50,100]",
                                   "100-250" = "(100,250]",
                                   "250-500" = "(250,500]",
                                   "500-1000" = "(500,1e+03]"
                                   )
         )

# shelter_sizes <- c("(0-5]""0-5", "5-10", "10-25", "25-50", "50-100", "100-250", "250-500", "500-1000")
```


```{r}
shelters_2019_cap_by_sec_size <- shelters_2019_cap_by_sec_size %>% 
  mutate(sector = factor(sector, levels = c("Women", "Men", "Youth", "Co-ed", "Families")))
```


```{r}
library(viridis)

p <- ggplot(data = shelters_2019_cap_by_sec_size,
            mapping = aes(x = sector, y = prop_cap, fill = forcats::fct_rev(shelter_size)
                          )
            )

p + geom_bar(stat = "identity", colour = "gray80") +
  
  scale_y_continuous(labels = scales::percent) +
  scale_fill_viridis(discrete = TRUE) +
  
  guides(fill = guide_legend(reverse = TRUE,
                             title.position = "top",
                             label.position = "bottom",
                             keywidth = 3,
                             nrow = 1)
         ) +
  
  labs(x = "Shelter type\n", y = "\nPercentage of shelter capacity",
       fill = "Capacity of shelter (number of people)",
       title = "Shelter capacity in Toronto (2019), by shelter type and shelter size",
       subtitle = "Families are more likley to find themselves in large shelters than individuals\n",
       caption = "Source: open.toronto.ca\nFigure insipred by: socviz.co") +
  
  theme_minimal() +
  theme(legend.position = "top") +
  
  coord_flip()
```



